version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_PASSWORD: example
      PG_DATABASE: postgres
    depends_on:
      - postgres
  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: example
